http:
  port: 8080

admin:
  port: 9876
  host: localhost

apiEndpoints:
  order-api:
    host: 'localhost'
    paths:
      - '/order/*'
      - '/quiz/*'
      - '/suggestion/*'
  user-public-api:
    host: 'localhost'
    paths:
      - '/user/register'
      - '/user/login'
  user-api:
    host: 'localhost'
    paths: '/user/*'
  admin-api:
    host: 'localhost'
    paths: '/admin/*'
  alert-api:
    host: 'localhost'
    paths: '/alert/*'
  wallet-api:
    host: 'localhost'
    paths: '/wallet/*'
  history-api:
    host: 'localhost'
    paths: '/history/*'
  walletLogin-api:
    host: 'localhost'
    paths: '/walletLogin/*'
  seedphrase-api:
    host: 'localhost'
    paths: '/seedphrase/*'
  education-api:
    host: 'localhost'
    paths: '/education/*'
  forum-api:
    host: 'localhost'
    paths: '/forum/*'
  answers-api:
    host: 'localhost'
    paths: '/answers/*'
  news-api:
    host: 'localhost'
    paths: '/news/*'
  asset-api:
    host: 'localhost'
    paths: '/portfolio/asset/*'
  value-api:
    host: 'localhost'
    paths: '/portfolio/value/*'
  address-api:
    host: 'localhost'
    paths: '/portfolio/address/*'
  portHistory-api:
    host: 'localhost'
    paths: '/portfolio/history/*'
  watchList-api:
    host: 'localhost'
    paths: '/watchList/*'

serviceEndpoints:
  order-service:
    url: 'http://localhost:8005'
  quiz-service:
    url: 'http://localhost:8005'
  suggestion-service:
    url: 'http://localhost:8005'
  user-service:
    url: 'http://localhost:8004'
  admin-service:
    url: 'http://localhost:8003'
  alert-service:
    url: 'http://localhost:8002'
  wallet-service:
    url: 'http://localhost:8006'
  history-service:
    url: 'http://localhost:8006'
  walletLogin-service:
    url: 'http://localhost:8006'
  seedphrase-service:
    url: 'http://localhost:8006'
  education-service:
    url: 'http://localhost:8009'
  forum-service:
    url: 'http://localhost:8010'
  answers-service:
    url: 'http://localhost:8010'
  news-service:
    url: 'http://localhost:8008'
  asset-service:
    url: 'http://localhost:8011'
  value-service:
    url: 'http://localhost:8011'
  address-service:
    url: 'http://localhost:8011'
  portHistory-service:
    url: 'http://localhost:8011'
  watchList-service:
    url: 'http://localhost:8007'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt

pipelines:
  order-pipeline:
    apiEndpoints:
      - order-api
    policies:
      - cors:
          - action:
              origin: 'http://localhost:3000'
              methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
              headers: [ 'Authorization', 'Content-Type' ]
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: order-service
              changeOrigin: true
  user-public-pipeline:
    apiEndpoints:
      - user-public-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: user-service
              changeOrigin: true
  user-pipeline:
    apiEndpoints:
      - user-api
    policies:
      - cors:
          - action:
              origin: 'http://localhost:3000'
              methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
              headers: [ 'Authorization', 'Content-Type' ]
      - jwt:
          - action:
              secretOrPublicKey: ${env.JWT_SECRET}
              algorithms: [ 'HS256' ]
      - proxy:
          - action:
              serviceEndpoint: user-service
              changeOrigin: true
  admin-pipeline:
    apiEndpoints:
      - admin-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: admin-service
              changeOrigin: true
  alert-pipeline:
    apiEndpoints:
      - alert-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: alert-service
              changeOrigin: true
  wallet-pipeline:
    apiEndpoints:
      - wallet-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: wallet-service
              changeOrigin: true
  history-pipeline:
    apiEndpoints:
      - history-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: history-service
              changeOrigin: true
  walletLogin-pipeline:
    apiEndpoints:
      - walletLogin-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: walletLogin-service
              changeOrigin: true
  seedphrase-pipeline:
    apiEndpoints:
      - seedphrase-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: seedphrase-service
              changeOrigin: true
  education-pipeline:
    apiEndpoints:
      - education-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: education-service
              changeOrigin: true
  forum-pipeline:
    apiEndpoints:
      - forum-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: forum-service
              changeOrigin: true
  answers-pipeline:
    apiEndpoints:
      - answers-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: answers-service
              changeOrigin: true
  news-pipeline:
    apiEndpoints:
      - news-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: news-service
              changeOrigin: true
  asset-pipeline:
    apiEndpoints:
      - asset-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: asset-service
              changeOrigin: true
  value-pipeline:
    apiEndpoints:
      - value-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: value-service
              changeOrigin: true
  address-pipeline:
    apiEndpoints:
      - address-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: address-service
              changeOrigin: true
  portHistory-pipeline:
    apiEndpoints:
      - portHistory-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: portHistory-service
              changeOrigin: true
  watchList-pipeline:
    apiEndpoints:
      - watchList-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: watchList-service
              changeOrigin: true
